---
title: "Fisheries Data Cleaning"
author: "Dimitri Kasiouleris"
date: "5/1/2021"
output: pdf_document
---

Methods
```{r}
#List of kelp forest fish species 
##sheephead, sea urchin(all), rockfish, cabezon, spiny lobster, giant kelpfish,scorpionfish, giant sea bass, kelp bass
###Filter data to only include these species, and none else
```

```{r}
library(dplyr)
library(stringr)
```

Combined and Cleaned Fisheries Data
```{r}
eureka <- read.csv("Table16PUB_2019_ADA.csv")

bay_area <- read.csv("table17PUB_2019.csv")

monterey <- read.csv("Table18PUB_2019_ADA.csv")

sb <- read.csv("Table19PUB_2019_ADA.csv")

Sonoma <- read.csv("Table21BBPUB_2019_ADA.csv")

mendicino <- read.csv("Table21FBPUB_2019_ADA.csv")

mendicino <- rename(mendicino, Species = Species.Pounds.Value)

slo <- read.csv("Table21MBPUB_2019_ADA.csv")

san_diego <- read.csv("Table21SDPUB_2019_ADA.csv")

combined_data <- do.call("rbind", list(eureka, bay_area, monterey, sb, Sonoma, mendicino, slo, san_diego))

combined_data <- combined_data  %>% filter(str_detect(Species, "Rockfish|Sheephead|Sea Urchin|Cabezon|Lobster|Kelpfish|Scorpionfish|Sea Bass|Kelp Bass|Sea Urchin"))

combined_data[,c("Species", "Pounds")] <- NULL

combined_data <- combined_data %>% mutate(Value = as.numeric(Value))

combined_data <- combined_data %>% group_by(County) %>% summarise(total_value = sum(Value))

combined_data <- rename(combined_data, COUNTY_NAM = County)

combined_data$COUNTY_NAM <- str_remove(combined_data$COUNTY_NAM, "County")
```









